import { AlertProps } from '../Alert';
import { AnchorProps } from '../Anchor';
import { AvatarProps } from '../Avatar';
import { BadgeProps } from '../Badge';
import { BoxProps } from '../Box';
import { BreadcrumbProps } from '../Breadcrumb';
import { ButtonProps } from '../Button';
// import { CalendarProps } from '../Calendar';
import { CardGroupProps, CardProps } from '../Card';
import { CarouselProps } from '../Carousel';
import { CascaderProps } from '../Cascader';
import { CheckboxGroupProps, CheckboxProps } from '../Checkbox';
import { CollapseProps } from '../Collapse';
import { DatePickerProps } from '../DatePicker';
import { DescriptionsProps } from '../Descriptions';
import { DialogProps } from '../Dialog';
import { DividerProps } from '../Divider';
import { DrawerProps } from '../Drawer';
import { DropdownProps } from '../Dropdown';
import { ErrorBoundaryProps } from '../ErrorBoundary';
import { FloatButtonProps } from '../FloatButton';
import { FormProps } from '../Form';
import { GridProps } from '../Grid';
import { HighlightProps } from '../Highlight';
import { ImageViewerPopupProps, ImageViewerProps } from '../ImageViewer';
import { EmailProps } from '../Input';
import { InputNumberProps } from '../InputNumber';
import { LabelProps } from '../Label';
import { ListProps } from '../List';
import { MenuProps } from '../Menu';
import { RevealProps } from '../Reveal';
// import { MessageType } from '../Message';
import { InputProps, PasswordProps } from '../Input';
import { PaginationProps } from '../Pagination';
import { PopconfirmProps } from '../Popconfirm';
import { PopoverProps } from '../Popover';
import { ProgressProps } from '../Progress';
import { QRCodeProps } from '../QRCode';
import { RadioGroupProps, RadioProps } from '../Radio';
import { RangePickerProps } from '../RangePicker';
import { RateProps } from '../Rate';
import { SearchProps } from '../Search';
import { SegmentedProps } from '../Segmented';
import { SelectProps } from '../Select';
import { SkeletonProps } from '../Skeleton';
import { SliderProps } from '../Slider';
import { SpaceProps } from '../Space';
import { SplitterProps } from '../Splitter';
import { StepsProps } from '../Steps';
import { SwitchProps } from '../Switch';
import { TableProps } from '../Table';
import { TableSelectProps } from '../TableSelect';
import { TabsProps } from '../Tabs';
import { TagProps } from '../Tag';
import { TextAreaProps } from '../TextArea';
// import { TimePickerProps } from '../TimePicker';
import { SpinProps } from '../Spin';
import { TimelineProps } from '../Timeline';
import { TooltipProps } from '../Tooltip';
import { TourProps } from '../Tour';
import { TransferProps } from '../Transfer';
import { TreeProps } from '../Tree';
import { TreeSelectProps } from '../TreeSelect';
import { TriggerProps } from '../Trigger';
import { UploadProps } from '../Upload';
import { VerificationCodeProps } from '../VerificationCode';
import { WatermarkProps } from '../Watermark';

export type GlobalCtxType = {
  alert?: AlertProps;
  anchor?: AnchorProps;
  avatar?: AvatarProps;
  badge?: BadgeProps;
  box?: BoxProps;
  breadcrumb?: BreadcrumbProps;
  button?: ButtonProps;
  //   buttongroup?: ButtonGroupProps;
  //   calendar?: CalendarProps;
  card?: CardProps;
  cardgroup?: CardGroupProps;
  carousel?: CarouselProps;
  cascader?: CascaderProps;
  checkbox?: CheckboxProps;
  checkboxgroup?: CheckboxGroupProps;
  collapse?: CollapseProps;
  datepicker?: DatePickerProps;
  rangepicker?: RangePickerProps;
  dialog?: DialogProps;
  divider?: DividerProps;
  descriptions?: DescriptionsProps;
  drawer?: DrawerProps;
  dropdown?: DropdownProps;
  email?: EmailProps;
  errorboundary?: ErrorBoundaryProps;
  form?: FormProps;
  floatbutton?: FloatButtonProps;
  grid?: GridProps;
  inputnumber?: InputNumberProps;
  imageviewer?: ImageViewerProps;
  imageviewerpopup?: ImageViewerPopupProps;
  label?: LabelProps;
  reveal?: RevealProps;
  list?: ListProps;
  menu?: MenuProps;
  //   message?: MessageType;
  password?: PasswordProps;
  pagination?: PaginationProps;
  popconfirm?: PopconfirmProps;
  popover?: PopoverProps;
  progress?: ProgressProps;
  qrcode?: QRCodeProps;
  radio?: RadioProps;
  radiogroup?: RadioGroupProps;
  rate?: RateProps;
  search?: SearchProps;
  select?: SelectProps;
  segmented?: SegmentedProps;
  skeleton?: SkeletonProps;
  slider?: SliderProps;
  space?: SpaceProps;
  spin?: SpinProps;
  splitter?: SplitterProps;
  steps?: StepsProps;
  switch?: SwitchProps;
  table?: TableProps;
  tableselect?: TableSelectProps;
  tabs?: TabsProps;
  tag?: TagProps;
  input?: InputProps;
  textarea?: TextAreaProps;
  timeline?: TimelineProps;
  highlight?: HighlightProps;
  //   timepicker?: TimePickerProps;
  tooltip?: TooltipProps;
  tour?: TourProps;
  transfer?: TransferProps;
  tree?: TreeProps<unknown>;
  treeselect?: TreeSelectProps;
  trigger?: TriggerProps;
  upload?: UploadProps;
  verificationcode?: VerificationCodeProps;
  watermark?: WatermarkProps;
};
