export default {
  language: 'zh_tw',
  weekList: ['周日', '週一', '週二', '週三', '週四', '週五', '週六', '周日'],
  shortWeekList: ['日', '一', '二', '三', '四', '五', '六', '日'],
  monthList: [
    '一月',
    '二月',
    '三月',
    '四月',
    '五月',
    '六月',
    '七月',
    '八月',
    '九月',
    '十月',
    '十一月',
    '十二月',
  ],
  shortMonthList: [
    '一',
    '二',
    '三',
    '四',
    '五',
    '六',
    '七',
    '八',
    '九',
    '十',
    '十一',
    '十二',
  ],
  timeList: ['時', '分', '秒'],
  APMList: ['上午', '下午'],
  selectTime: '選擇時間',
  returnDate: '選擇日期',
  now: '此刻',
  confirm: '確定',
};
